version: '3'
services:
  wp_database:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 6454FLOCK
      MYSQL_DATABASE: wp_db
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: 6454flock
    volumes:
      - mysql-data:/var/lib/
  wp_source:
    depends_on:
      - wp_database
    image: wordpress:latest
    restart: unless-stopped
    environment:  
      WORDPRESS_DB_HOST: wp_database:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: 6454flock
      WORDPRESS_DB_NAME:  wp_db
    ports:  
      - 8000:80
    volumes:
      - wp-data:/var/www/html
volumes:
  mysql-data: {}
  wp-data: {}
